# Examples
## SK_Learn Multiple Linear Regression
### Import Relevant Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set()

### Load Data

In [2]:
file_path = 'C:/Users/iolley2/Desktop/DS Contd/Multiple Linear Regressions/Examples/1.02.+Multiple+linear+regression.csv'
data = pd.read_csv(file_path)

In [3]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [4]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

### Create Regression

#### Define dependent and independent variable

In [17]:
yname,x1name,x2name = 'GPA','SAT','Rand 1,2,3'
y = data[yname]
x1 = data[[x1name,x2name]]

In [19]:
reg = LinearRegression()
reg.fit(x1,y)

LinearRegression()

In [20]:
# Coefficients
reg.coef_

array([ 0.00165354, -0.00826982])

In [21]:
# Intercept
reg.intercept_

0.29603261264909486

In [23]:
# R-Squared
reg.score(x1,y)

0.40668119528142843

#### Adjusted R-Squared
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

###### n = number of observations
###### p = number of predictors

In [30]:
r2 = reg.score(x1,y) # R-Squared
n = x1.shape[0]
p = x1.shape[1]
adj_R2 = 1 - (1-r2)*(n-1)/(n-p-1)

In [31]:
adj_R2

0.39203134825134023

#### Feature Selection

In [32]:
from sklearn.feature_selection import f_regression

In [33]:
f_regression(x1,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [36]:
p_values = f_regression(x1,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [38]:
f_statistic = f_regression(x1,y)[0]
f_statistic

array([56.04804786,  0.17558437])

In [39]:
p_values.round(3)

array([0.   , 0.676])

### Create a summary table

In [45]:
reg_summary = pd.DataFrame(data = x1.columns.values,columns = ['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [44]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)
reg_summary['F-Statistic'] = f_statistic.round(3)
reg_summary

Features  Coefficients  p-values  F-Statistic
0         SAT      0.001654     0.000       56.048
1  Rand 1,2,3     -0.008270     0.676        0.176