# Applying machine learning (scalling the dummy variables)

###### Import library

In [5]:
import numpy as np
import pandas as pd

###### Load Data

In [6]:
data_preprocessed = pd.read_csv('C:/Users/iolley2/Desktop/DS Contd/Absenteeism Case/df_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

###### Create targets

We would be create 2 classes
1. People moderately absent
2. People Excessively absent

We would take the median value of the Absenteeism time in hours and below the median will be considered normal and above would be excessive

In [7]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [9]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [10]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

###### Comment on targets

In [12]:
targets.sum()/targets.shape[0]

0.45571428571428574

Around 46% of the targets are '1' (excessively absent) and 54% are '0'

Usually when creating models, we would like to have our classes as equally balanced as possible 50-50, 45-55

###### Checkpoint

In [13]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis = 1)

In [14]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [15]:
data_with_targets.shape

(700, 15)

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:14]
# or #data_with_targets.iloc[:,:-1]

###### Standardize data

In [17]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [18]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [19]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

###### Split data to train, test and shuffle data

In [20]:
from sklearn.model_selection import train_test_split

###### Split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size = 0.8,
                                                shuffle=True,random_state = 20)

In [31]:
print('train:',x_train.shape,y_train.shape,'\ntest:',x_test.shape,y_test.shape)

train: (560, 14) (560,) 
test: (140, 14) (140,)


###### Modelling: Logistic

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train,y_train)

LogisticRegression()

###### R_square

In [37]:
reg.score(x_train,y_train)

0.7839285714285714

###### Manually calculate r^2 (accuracy)

In [44]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [45]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [46]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [41]:
np.sum(model_output == y_train)

439

In [42]:
model_output.shape[0]

560

In [43]:
np.sum(model_output == y_train)/model_output.shape[0]

0.7839285714285714

###### Intercepts and coefficients

In [49]:
reg.intercept_

array([-0.22206736])

In [50]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.18793677,
        -0.07062253,  0.70639316, -0.03986811, -0.20089491, -0.00456366,
         0.31933564, -0.135508  ,  0.38172443, -0.3332426 ]])

In [52]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [53]:
feature_name = unscaled_inputs.columns.values

In [63]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)

In [64]:
summary_table['Coefficients'] = np.transpose(reg.coef_)

In [65]:
summary_table

Feature Name  Coefficients
0                  Reason_1      2.076018
1                  Reason_2      0.335048
2                  Reason_3      1.561623
3                  Reason_4      1.329274
4               Month Value      0.187937
5           Day of the Week     -0.070623
6    Transportation Expense      0.706393
7          Distance to Work     -0.039868
8                       Age     -0.200895
9   Daily Work Load Average     -0.004564
10          Body Mass Index      0.319336
11                Education     -0.135508
12                 Children      0.381724
13                     Pets     -0.333243

In [66]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficients
0                 Intercept     -0.222067
1                  Reason_1      2.076018
2                  Reason_2      0.335048
3                  Reason_3      1.561623
4                  Reason_4      1.329274
5               Month Value      0.187937
6           Day of the Week     -0.070623
7    Transportation Expense      0.706393
8          Distance to Work     -0.039868
9                       Age     -0.200895
10  Daily Work Load Average     -0.004564
11          Body Mass Index      0.319336
12                Education     -0.135508
13                 Children      0.381724
14                     Pets     -0.333243

###### Interpreting coefficients/weights

In [68]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficients)
summary_table

Feature Name  Coefficients  Odds_ratio
0                 Intercept     -0.222067    0.800861
1                  Reason_1      2.076018    7.972656
2                  Reason_2      0.335048    1.398007
3                  Reason_3      1.561623    4.766551
4                  Reason_4      1.329274    3.778301
5               Month Value      0.187937    1.206757
6           Day of the Week     -0.070623    0.931814
7    Transportation Expense      0.706393    2.026668
8          Distance to Work     -0.039868    0.960916
9                       Age     -0.200895    0.817998
10  Daily Work Load Average     -0.004564    0.995447
11          Body Mass Index      0.319336    1.376213
12                Education     -0.135508    0.873272
13                 Children      0.381724    1.464808
14                     Pets     -0.333243    0.716596

In [71]:
# Arranged from least important to most important
summary_table.sort_values('Odds_ratio',ascending=False)

Feature Name  Coefficients  Odds_ratio
1                  Reason_1      2.076018    7.972656
3                  Reason_3      1.561623    4.766551
4                  Reason_4      1.329274    3.778301
7    Transportation Expense      0.706393    2.026668
13                 Children      0.381724    1.464808
2                  Reason_2      0.335048    1.398007
11          Body Mass Index      0.319336    1.376213
5               Month Value      0.187937    1.206757
10  Daily Work Load Average     -0.004564    0.995447
8          Distance to Work     -0.039868    0.960916
6           Day of the Week     -0.070623    0.931814
12                Education     -0.135508    0.873272
9                       Age     -0.200895    0.817998
0                 Intercept     -0.222067    0.800861
14                     Pets     -0.333243    0.716596

If a coefficient is around 0 or odds ratio = 1, it implies the corresponding feature is not particularly important

Given the above statement, [Daily work load average, distance to work, day of the week] do not make any difference

It is seen that provided a worker provided a reason of absence, there is a higher chance of excessive absence from work