# Applying machine learning (unscaled the dummy variables) - Backward Elimination

###### Import library

In [1]:
import numpy as np
import pandas as pd

###### Load Data

In [2]:
data_preprocessed = pd.read_csv('C:/Users/iolley2/Desktop/DS Contd/Absenteeism Case/df_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

###### Create targets

We would be create 2 classes
1. People moderately absent
2. People Excessively absent

We would take the median value of the Absenteeism time in hours and below the median will be considered normal and above would be excessive

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

###### Comment on targets

In [6]:
targets.sum()/targets.shape[0]

0.45571428571428574

Around 46% of the targets are '1' (excessively absent) and 54% are '0'

Usually when creating models, we would like to have our classes as equally balanced as possible 50-50, 45-55

###### Checkpoint

In [7]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Age',
                                           'Body Mass Index','Transportation Expense'],axis = 1)

In [8]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Distance to Work  Daily Work Load Average  Education  Children  Pets  \
0                36                  239.554          0         2     1   
1                13                  239.554          0         1     0   
2                51                  239.554          0         0     0   
3                 5                  239.554          0         2     0   
4                36                  239.554          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
data_with_targets.shape

(700, 12)

In [10]:
unscaled_inputs = data_with_targets.iloc[:,:14]
# or #data_with_targets.iloc[:,:-1]

###### Standardize data

In [11]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

###### Seperater dummy data and data to be scaled

In [12]:
dummies = unscaled_inputs[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']]
to_scale = unscaled_inputs[['Month Value',
       'Day of the Week', 'Distance to Work',
       'Daily Work Load Average', 
       'Children', 'Pets']]

In [13]:
absenteeism_scaler.fit(to_scale)
scaled_inputs_no_dummies = absenteeism_scaler.transform(to_scale)

In [14]:
dummies = dummies.to_numpy()
dummies

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       ...,
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0]], dtype=int64)

In [15]:
dummies.shape,scaled_inputs_no_dummies.shape

((700, 5), (700, 6))

In [16]:
scaled_inputs = np.concatenate((dummies,scaled_inputs_no_dummies),axis=1)

In [17]:
scaled_inputs

array([[ 0.        ,  0.        ,  0.        , ..., -0.80633129,
         0.88046927,  0.26848661],
       [ 0.        ,  0.        ,  0.        , ..., -0.80633129,
        -0.01928035, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ..., -0.80633129,
        -0.91902997, -0.58968976],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.85378935,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ..., -0.85378935,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ..., -0.85378935,
        -0.01928035,  0.26848661]])

###### Split data to train, test and shuffle data

###### Split

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size = 0.8,
                                                shuffle=True,random_state = 20)

In [19]:
print('train:',x_train.shape,y_train.shape,'\ntest:',x_test.shape,y_test.shape)

train: (560, 11) (560,) 
test: (140, 11) (140,)


###### Modelling: Logistic

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [21]:
reg = LogisticRegression()

In [22]:
reg.fit(x_train,y_train)

LogisticRegression()

###### R_square

In [23]:
reg.score(x_train,y_train)

0.7410714285714286

###### Manually calculate r^2 (accuracy)

In [24]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [25]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [26]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,

In [27]:
np.sum(model_output == y_train)

415

In [28]:
model_output.shape[0]

560

In [29]:
np.sum(model_output == y_train)/model_output.shape[0]

0.7410714285714286

###### Intercepts and coefficients

In [30]:
reg.intercept_

array([-1.5163374])

In [31]:
reg.coef_

array([[ 2.63819239,  0.71232194,  2.782904  ,  0.71995328, -0.17488631,
         0.23216798, -0.09708332,  0.14405361, -0.01626046,  0.49102544,
        -0.05888924]])

In [32]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Distance to Work', 'Daily Work Load Average',
       'Education', 'Children', 'Pets', 'Excessive Absenteeism'],
      dtype=object)

In [37]:
feature_name = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Distance to Work', 'Daily Work Load Average',
       'Education', 'Children', 'Pets']

In [38]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)

In [39]:
summary_table

Feature Name
0                  Reason_1
1                  Reason_2
2                  Reason_3
3                  Reason_4
4               Month Value
5           Day of the Week
6          Distance to Work
7   Daily Work Load Average
8                 Education
9                  Children
10                     Pets

In [40]:
summary_table['Coefficients'] = np.transpose(reg.coef_)

In [41]:
summary_table

Feature Name  Coefficients
0                  Reason_1      2.638192
1                  Reason_2      0.712322
2                  Reason_3      2.782904
3                  Reason_4      0.719953
4               Month Value     -0.174886
5           Day of the Week      0.232168
6          Distance to Work     -0.097083
7   Daily Work Load Average      0.144054
8                 Education     -0.016260
9                  Children      0.491025
10                     Pets     -0.058889

In [42]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficients
0                 Intercept     -1.516337
1                  Reason_1      2.638192
2                  Reason_2      0.712322
3                  Reason_3      2.782904
4                  Reason_4      0.719953
5               Month Value     -0.174886
6           Day of the Week      0.232168
7          Distance to Work     -0.097083
8   Daily Work Load Average      0.144054
9                 Education     -0.016260
10                 Children      0.491025
11                     Pets     -0.058889

###### Interpreting coefficients/weights

In [43]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficients)
summary_table

Feature Name  Coefficients  Odds_ratio
0                 Intercept     -1.516337    0.219514
1                  Reason_1      2.638192   13.987896
2                  Reason_2      0.712322    2.038720
3                  Reason_3      2.782904   16.165899
4                  Reason_4      0.719953    2.054337
5               Month Value     -0.174886    0.839552
6           Day of the Week      0.232168    1.261332
7          Distance to Work     -0.097083    0.907480
8   Daily Work Load Average      0.144054    1.154946
9                 Education     -0.016260    0.983871
10                 Children      0.491025    1.633991
11                     Pets     -0.058889    0.942811

In [44]:
# Arranged from least important to most important
summary_table.sort_values('Odds_ratio',ascending=False)

Feature Name  Coefficients  Odds_ratio
3                  Reason_3      2.782904   16.165899
1                  Reason_1      2.638192   13.987896
4                  Reason_4      0.719953    2.054337
2                  Reason_2      0.712322    2.038720
10                 Children      0.491025    1.633991
6           Day of the Week      0.232168    1.261332
8   Daily Work Load Average      0.144054    1.154946
9                 Education     -0.016260    0.983871
11                     Pets     -0.058889    0.942811
7          Distance to Work     -0.097083    0.907480
5               Month Value     -0.174886    0.839552
0                 Intercept     -1.516337    0.219514

###### Testing the model

In [45]:
reg.score(x_test,y_test)

0.7071428571428572

Get the probability of an output being zero or one

In [46]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.69614256, 0.30385744],
       [0.68470984, 0.31529016],
       [0.60655567, 0.39344433],
       [0.79256425, 0.20743575],
       [0.05438012, 0.94561988],
       [0.30147329, 0.69852671],
       [0.18697245, 0.81302755],
       [0.18390182, 0.81609818],
       [0.79334952, 0.20665048],
       [0.72133873, 0.27866127],
       [0.62540457, 0.37459543],
       [0.50608235, 0.49391765],
       [0.07558809, 0.92441191],
       [0.77904138, 0.22095862],
       [0.19009475, 0.80990525],
       [0.85776615, 0.14223385],
       [0.69797942, 0.30202058],
       [0.73540047, 0.26459953],
       [0.22314273, 0.77685727],
       [0.09425845, 0.90574155],
       [0.64927005, 0.35072995],
       [0.78156771, 0.21843229],
       [0.27964799, 0.72035201],
       [0.30683542, 0.69316458],
       [0.2805154 , 0.7194846 ],
       [0.73920493, 0.26079507],
       [0.64044392, 0.35955608],
       [0.79853122, 0.20146878],
       [0.19296885, 0.80703115],
       [0.77015728, 0.22984272],
       [0.

With two columns, the first column shows the probability our model assigned to the observation being zero and the second, the probability, the model assigned to the observation being one. That's why summing any two numbers horizontally will give you an output of one.

In [48]:
# Probability of excessive absenteeism
predicted_proba[:,1]

array([0.30385744, 0.31529016, 0.39344433, 0.20743575, 0.94561988,
       0.69852671, 0.81302755, 0.81609818, 0.20665048, 0.27866127,
       0.37459543, 0.49391765, 0.92441191, 0.22095862, 0.80990525,
       0.14223385, 0.30202058, 0.26459953, 0.77685727, 0.90574155,
       0.35072995, 0.21843229, 0.72035201, 0.69316458, 0.7194846 ,
       0.26079507, 0.35955608, 0.20146878, 0.80703115, 0.22984272,
       0.29185374, 0.69481701, 0.69920858, 0.40546879, 0.21843229,
       0.320294  , 0.22081568, 0.77825383, 0.39203437, 0.66264378,
       0.23842546, 0.51384258, 0.22806608, 0.50155814, 0.72144794,
       0.62506949, 0.77080839, 0.31458958, 0.16761207, 0.1809151 ,
       0.71691214, 0.13307123, 0.67380522, 0.2659806 , 0.80638436,
       0.40702369, 0.77458627, 0.34130379, 0.18446227, 0.18635502,
       0.61084938, 0.66625196, 0.43583126, 0.79264127, 0.30885155,
       0.30590785, 0.14407083, 0.2413571 , 0.64372225, 0.27032414,
       0.21814557, 0.09878194, 0.81836584, 0.40638544, 0.46596

If the probability is less than 0.5, it places a '0' else it places a '1'

###### Saving the model

In [50]:
import pickle

In [51]:
with open('model','wb') as file :
    pickle.dump(reg, file)