# Applying machine learning (unscaled the dummy variables)

###### Import library

In [2]:
import numpy as np
import pandas as pd

###### Load Data

In [3]:
data_preprocessed = pd.read_csv('C:/Users/iolley2/Desktop/DS Contd/Absenteeism Case/df_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

###### Create targets

We would be create 2 classes
1. People moderately absent
2. People Excessively absent

We would take the median value of the Absenteeism time in hours and below the median will be considered normal and above would be excessive

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

###### Comment on targets

In [7]:
targets.sum()/targets.shape[0]

0.45571428571428574

Around 46% of the targets are '1' (excessively absent) and 54% are '0'

Usually when creating models, we would like to have our classes as equally balanced as possible 50-50, 45-55

###### Checkpoint

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis = 1)

In [9]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [11]:
data_with_targets.shape

(700, 15)

In [15]:
unscaled_inputs = data_with_targets.iloc[:,:14]
# or #data_with_targets.iloc[:,:-1]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

###### Standardize data

In [17]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

###### Seperater dummy data and data to be scaled

In [18]:
dummies = unscaled_inputs[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']]
to_scale = unscaled_inputs[['Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets']]


In [19]:
absenteeism_scaler.fit(to_scale)
scaled_inputs_no_dummies = absenteeism_scaler.transform(to_scale)

In [20]:
dummies = dummies.to_numpy()
dummies

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       ...,
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0]], dtype=int64)

In [21]:
dummies.shape,scaled_inputs_no_dummies.shape

((700, 5), (700, 9))

In [22]:
scaled_inputs = np.concatenate((dummies,scaled_inputs_no_dummies),axis=1)

In [23]:
scaled_inputs

array([[ 0.        ,  0.        ,  0.        , ...,  0.76743118,
         0.88046927,  0.26848661],
       [ 0.        ,  0.        ,  0.        , ...,  1.00263338,
        -0.01928035, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  1.00263338,
        -0.91902997, -0.58968976],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.40857982,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ..., -0.40857982,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ..., -0.40857982,
        -0.01928035,  0.26848661]])

###### Split data to train, test and shuffle data

###### Split

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size = 0.8,
                                                shuffle=True,random_state = 20)

In [25]:
print('train:',x_train.shape,y_train.shape,'\ntest:',x_test.shape,y_test.shape)

train: (560, 14) (560,) 
test: (140, 14) (140,)


###### Modelling: Logistic

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [27]:
reg = LogisticRegression()

In [28]:
reg.fit(x_train,y_train)

LogisticRegression()

###### R_square

In [29]:
reg.score(x_train,y_train)

0.775

###### Manually calculate r^2 (accuracy)

In [30]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [31]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [32]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [33]:
np.sum(model_output == y_train)

434

In [34]:
model_output.shape[0]

560

In [35]:
np.sum(model_output == y_train)/model_output.shape[0]

0.775

###### Intercepts and coefficients

In [36]:
reg.intercept_

array([-1.6561092])

In [37]:
reg.coef_

array([[ 2.80096498e+00,  9.34857518e-01,  3.09561645e+00,
         8.56587468e-01, -2.05738037e-01,  1.66248119e-01,
        -8.43703301e-02,  6.12732578e-01, -7.79685996e-03,
        -1.65922708e-01, -1.47005122e-04,  2.71811477e-01,
         3.61989880e-01, -2.85510745e-01]])

In [38]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [39]:
feature_name = unscaled_inputs.columns.values

In [40]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)

In [41]:
summary_table['Coefficients'] = np.transpose(reg.coef_)

In [42]:
summary_table

Feature Name  Coefficients
0                  Reason_1      2.800965
1                  Reason_2      0.934858
2                  Reason_3      3.095616
3                  Reason_4      0.856587
4               Month Value     -0.205738
5           Day of the Week      0.166248
6    Transportation Expense     -0.084370
7          Distance to Work      0.612733
8                       Age     -0.007797
9   Daily Work Load Average     -0.165923
10          Body Mass Index     -0.000147
11                Education      0.271811
12                 Children      0.361990
13                     Pets     -0.285511

In [43]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficients
0                 Intercept     -1.656109
1                  Reason_1      2.800965
2                  Reason_2      0.934858
3                  Reason_3      3.095616
4                  Reason_4      0.856587
5               Month Value     -0.205738
6           Day of the Week      0.166248
7    Transportation Expense     -0.084370
8          Distance to Work      0.612733
9                       Age     -0.007797
10  Daily Work Load Average     -0.165923
11          Body Mass Index     -0.000147
12                Education      0.271811
13                 Children      0.361990
14                     Pets     -0.285511

###### Interpreting coefficients/weights

In [44]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficients)
summary_table

Feature Name  Coefficients  Odds_ratio
0                 Intercept     -1.656109    0.190880
1                  Reason_1      2.800965   16.460523
2                  Reason_2      0.934858    2.546851
3                  Reason_3      3.095616   22.100858
4                  Reason_4      0.856587    2.355110
5               Month Value     -0.205738    0.814046
6           Day of the Week      0.166248    1.180866
7    Transportation Expense     -0.084370    0.919091
8          Distance to Work      0.612733    1.845467
9                       Age     -0.007797    0.992233
10  Daily Work Load Average     -0.165923    0.847112
11          Body Mass Index     -0.000147    0.999853
12                Education      0.271811    1.312340
13                 Children      0.361990    1.436184
14                     Pets     -0.285511    0.751630

In [45]:
# Arranged from least important to most important
summary_table.sort_values('Odds_ratio',ascending=False)

Feature Name  Coefficients  Odds_ratio
3                  Reason_3      3.095616   22.100858
1                  Reason_1      2.800965   16.460523
2                  Reason_2      0.934858    2.546851
4                  Reason_4      0.856587    2.355110
8          Distance to Work      0.612733    1.845467
13                 Children      0.361990    1.436184
12                Education      0.271811    1.312340
6           Day of the Week      0.166248    1.180866
11          Body Mass Index     -0.000147    0.999853
9                       Age     -0.007797    0.992233
7    Transportation Expense     -0.084370    0.919091
10  Daily Work Load Average     -0.165923    0.847112
5               Month Value     -0.205738    0.814046
14                     Pets     -0.285511    0.751630
0                 Intercept     -1.656109    0.190880

1. Reason_1: Various diseases
2. Reason_2: Pregnancy and Giving birth
3. Reason_3: Poisoning
4. Reason_4: Light Diseases
5. Reason_0: No reason

1. we will notice that the most strongly pronounced features seem to be the four reasons for absence , the transportation expense and whether a person has children, pets and education.
2. Note that pet and education are at the bottom of the table, but their weights are still far away from zero. So they are indeed important.
3. Body Mass Index, age,Transportation Expense, which seem to have the smallest impact, their weight is almost zero. So regardless of the particular values, they will barely affect the model.

1. For Reason_3: 
The weight means the odds of someone being excessively absent after being poisoned are 22 times higher than when no reason was reported.
2. For Reason_1: A person who was reported this is 16 times more likely to be excessively absent than a person who didn't specify a reason

3. For Distance to work which is a standardized unit, its interpretation is different
    - It's odds ratio implies that for one standardized unit or for one standard deviation increase in transportation expense, it is close to twice as likely to be excessively absent.

4. For pets with a negative coefficient
    - Pet is a continuous variable, its odds ratio is zero point seven, so for each additional standardized unit of PET, the odds are one minus its odds ratio or twenty four percent lower than the base bottle.
    - One explanation may be if you have several pets, you're probably not taking care of them on your own Not being solely responsible for them implies somebody else can take them to the doctor if something is wrong.