# Train Test Split Example
## Import Libraries

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate/import data

In [6]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [21]:
c = np.arange(501,601)
c

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split data

In [17]:
train_test_split(a,random_state =1)

[array([ 36,  95,  28,  47,  39,  68, 100,  55,  96,  89,  41,  49,  60,
         24,  35,  87,  54,  78,  16,  84,  42,  46,  92,  27,  99,  44,
         56,  25,   5,  59,  50,  22,  88,   4,  75,  31,  67,  71,  43,
         48,  90,   9,  61,   1,  91,  58,  23,  62,  64,   8,  97,  14,
         69,  86,  15,  30,  29,  12,  19,  21,  51,  26,   7,  72,  77,
          2,  17,  65,  80,   6,  76,  10,  73,  13,  38]),
 array([81, 85, 34, 82, 94, 18, 37, 83, 70, 66, 93, 40, 57, 53, 52, 33, 32,
        45, 79, 11,  3, 74, 98, 63, 20])]

In [13]:
a_train,a_test = train_test_split(a,test_size = 0.2)

## Explore  the result

In [14]:
a_train.shape, a_test.shape # check the shapes

((80,), (20,))

In [23]:
train_test_split(a,b,c,c,test_size = 0.2)

[array([ 25,   5,  17,  75,  31,  15,  41,  93,  29,   6,  76,  96,  18,
         43,  47,  57,  84,  58,  87,   4,  99,   3,  67,   8,  46,  79,
         10,  74,  72,  59,  27,  88,  11,  23,  49,  42,  78,  60,  30,
         44,  61,  77, 100,  94,  70,  24,  81,  21,  53,  52,  37,  68,
         55,  73,  56,  16,  85,  54,  97,  28,  39,  86,  83,  45,  80,
         90,  63,  22,  51,  91,   2,  64,  19,  36,  66,   7,  38,  12,
         98,  82]),
 array([34, 20, 33, 89, 50, 65, 26,  1, 62, 69, 35, 92, 40, 13,  9, 14, 71,
        32, 95, 48]),
 array([525, 505, 517, 575, 531, 515, 541, 593, 529, 506, 576, 596, 518,
        543, 547, 557, 584, 558, 587, 504, 599, 503, 567, 508, 546, 579,
        510, 574, 572, 559, 527, 588, 511, 523, 549, 542, 578, 560, 530,
        544, 561, 577, 600, 594, 570, 524, 581, 521, 553, 552, 537, 568,
        555, 573, 556, 516, 585, 554, 597, 528, 539, 586, 583, 545, 580,
        590, 563, 522, 551, 591, 502, 564, 519, 536, 566, 507, 538, 512,
      